### ISSUE TITLE
accept kana combination cards

### ISSUE THREAD

**Issue by cayennes** [cayennes/kanji-colorize#36]
(from an email)

Things like じゃ as the full content should have diagrams.

Desired behavior:
* If there are kanji on the card, only do diagrams for the kanji. Some people want diagrams for the kanji in their sentences.
* Otherwise do diagrams for everything.

Bonus:
* Add a setting that can let people optionally always have diagrams for everything.

**Comment by emekoi** [comment]
this doesn't seem like a difficult fix, but where did you get the bounds for [this](https://github.com/cayennes/kanji-colorize/blob/3e571ffcc75c051939144f18c7d81d7a7735c5ce/anki/kanji_colorizer.py#L91) function? they seem completely wrong.

**Comment by cayennes** [comment]
Those numbers come from the unicode values of the kanji range to differentiate kanji from other characters. You're right this is an easy fix; it just needs the conditional to check whether the string has kanji rather than whether it is a single character.

I've updated the description to specify what the actual desired behavior is.
