### ISSUE TITLE
Editing Bug

### ISSUE THREAD

**Issue by Quinnlet** [cayennes/kanji-colorize#41]
I keep getting this error when editing my deck:

Traceback (most recent call last):
File "aqt/progress.pyc", line 69, in handler
File "aqt/editor.pyc", line 468, in onUpdate
File "aqt/editor.pyc", line 540, in loadNote
AttributeError: 'NoneType' object has no attribute 'media'

It shows the "click here to resume" screen when coming out of editing, and does it every time I edit my cards and it forces me to restart Anki - this can be quite frustrating when having to edit multiple cards, and it really is a shame as this addon is so useful!

**Comment by cayennes** [comment]
Thanks for the report.

Can you create a one-card deck that reproduces the issue and attach it here?

**Comment by cayennes** [comment]
(Also I don't make any promises about when I will find time to work on this)

**Comment by alexpizarroj** [comment]
I've finished working on a fix for this! Please let me know what you think.

**Comment by cayennes** [comment]
Thanks both of you! I'll have time to look at this and should be able to make a new release tomorrow

**Comment by Quinnlet** [comment]
Looking forward to the new release! I'll keep an eye out on Anki addon site. Thanks so much for quickness, and also have a merry xmas. :P

**Comment by cayennes** [comment]
I've fixed it and uploaded the new version.
