### ISSUE TITLE
Composita of Kanji

### ISSUE THREAD

**Issue by Moonlanced** [cayennes/kanji-colorize#43]
Hey,
Thank you for your tool, it helped me a ton when I made my own flashcards!

I am now having often times vocabulary with more than 1 kanji. And it would be cool (at least in my eyes) when you could add the first meaning of the kanji under the diagram when there is more than 1 Kanji in the diagram.

**Comment by cayennes** [comment]
the meanings of the kanji are out of scope for this addon
