### ISSUE TITLE
Update to Anki 2.1

### ISSUE THREAD

**Issue by Nebulean** [cayennes/kanji-colorize#45]
It would be great to have this addon updated to Anki 2.1.

I am trying to get the addon work with 2.1, but with the fact that python isn't a language I worked that much with, and that I've never done a Anki addon before, it's quite hard for me. I'll see if it's possible for me to do it.

The docs for 2.1.x addons is [here](https://apps.ankiweb.net/docs/addons.html).

(btw, thanks for this addon, it's a must-have for Anki in japanese !)

**Comment by j-kramer** [comment]
I also tried porting this addon a while ago, so today I cleaned it up a little bit into PR #46. Still it would be nice if you could also take a look at it, since like you also am not familiar with python.

**Comment by j-kramer** [comment]
The updated version is now available on ankiweb, so this issue can probably be closed.

**Comment by cayennes** [comment]
Yup, thanks.
