### ISSUE TITLE
Colorsys error on loading

### ISSUE THREAD

**Issue by psychodelicwasabi** [cayennes/kanji-colorize#49]
Some browsing revealed that something like this happened in the past. My machine is a Windows 10 64x, everything was working nicely until I updated the add-ons last night. I tried to uninstall and install it again, but the issue persists. I just wanted to give you a heads up about it, no pressure.

<img src="https://i.imgur.com/BMBJp2d.png">

**Comment by Luigi-Ranno** [comment]
Same as above, add-on fails to load in my machine as well (Macbook Pro running the Mojave OS version 10.14.6). The error message I got is also identical to the one posted above

**Comment by BioBlobber** [comment]
I have the same issue as the first post on Windows 10 (64 bit)

**Comment by cayennes** [comment]
Thanks for letting me know. I think I found what I did wrong, and have tested a new packaged version and it works for me. If the new version still doesn't work for you, let me know.

**Comment by BioBlobber** [comment]
Thank you for fixing it so quickly! Keep up the good work, this is a really useful tool!
