### ISSUE TITLE
investigate bug with generate all new

### ISSUE THREAD

**Issue by cayennes** [cayennes/kanji-colorize#55]
I got an email reporting this stack trace when trying to generate all new:    
```
Caught exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1964372878\kanji_colorizer.py", line 176, in generate_for_new
    for note_id in mw.col.findNotes(search_str):
  File "lib\site-packages\anki\collection.py", line 619, in find_notes
  File "lib\site-packages\anki\rsbackend.py", line 495, in search_notes
  File "lib\site-packages\anki\rsbackend.py", line 257, in _run_command
anki.rsbackend.StringError: InvalidInput { info: "unable to parse search" }
```

**Comment by cayennes** [comment]
It's not obvious what could cause this and it's not happening for me. I've asked for a minimal deck that can triggers it.

**Comment by cayennes** [comment]
I haven't heard back. I'll probably close this.

**Comment by NoelDeMartin** [comment]
Hey I'm getting this error on a new deck, is there something I can do to help you debug?

I am trying to do it on this deck: [All in One Kanji Deck (Heisig's RTK Order, 6th edition)](https://ankiweb.net/shared/info/1862058740). I've only changed the order of some fields and the html/styles of the cards.

I'm using Anki desktop on Ubuntu 18.04 with these versions:
Version 2.1.35 (84dcaa86)
Python 3.8.1 Qt 5.15.1 PyQt 5.15.1

**Comment by cayennes** [comment]
I found that this happens if `src-field`, `dst-fields`, or `model` is wrong and there are no models that match. Have you checked those?

I'll add an error message so it doesn't just fail like this.

**Comment by NoelDeMartin** [comment]
@cayennes Thank you, the problem is solved! I didn't have a model named "japanese" and that was the issue.

I just started using Anki and I didn't even know what a model was, but I think a message saying that the model is invalid or not found should be enough.
