### ISSUE TITLE
Hi there,

### ISSUE THREAD

**Issue by magychan35** [cayennes/kanji-colorize#58]
Can you please let me know if you can help me with creating animated kanji letters stroke orders so I can edited in my tutorials videos to my students?

**Comment by cayennes** [comment]
Sorry, it's not high enough priority for my limited time to add animations. Animations are fun but they don't add any additional information. If you or someone else does the work I would be happy to review a pull request though.
magychan35 <notifications@github.com> wrote:
“Can you please let me know if you can help me with creating animated kanji letters stroke orders so I can edited in my tutorials videos to my students?”
