### ISSUE TITLE
Option to prevent changing field if something is in it.

### ISSUE THREAD

**Issue by AndrewReitz** [cayennes/kanji-colorize#64]
This is a feature request to allow an option in the settings of the plugin to not input anything if the destination field already has something in it.

The use case is that I typed something in the field with the diagrams or maybe only want a subset of the diagrams so I delete the others and then when coming back later to edit the card I wouldn't want the plugin to overwrite what's already there.

If you're on board with this idea, I'm willing to try and implement it if you're low on time.

**Comment by cayennes** [comment]
Yes, it would be great if you could implement that feature. Let me know if you need any pointers.

**Comment by AndrewReitz** [comment]
#65
