### ISSUE TITLE
Readme Typo

### ISSUE THREAD

**Issue by aceamarco** [cayennes/kanji-colorize#75]
Hello @cayennes! Thank you for this amazing library I've been using your Anki add on for a year now and I've loved it.

I'm excited to use your repo now to work on my own personal projects. After cloning this repo and trying to run `kanji_colorize.py` I get the following error:

```shell
Traceback (most recent call last):
  File "/Users/macea/devel/github/kanji-trainer/kanji-colorize/kanji_colorize.py", line 28, in <module>
    kc.write_all()
  File "/Users/macea/devel/github/kanji-trainer/kanji-colorize/kanjicolorizer/colorizer.py", line 367, in write_all
    characters = KanjiVG.get_all()
  File "/Users/macea/devel/github/kanji-trainer/kanji-colorize/kanjicolorizer/colorizer.py", line 182, in get_all
    for file in os.listdir(source_directory):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/macea/devel/github/kanji-trainer/kanji-colorize/kanjicolorizer/data/kanjivg/kanji'
```

and I think this might have to do with a part of the readme but I think the example you meant to show isn't there.

`The first time you clone the project, you need to get the sub module with the uncolored diagrams:`

I'd really appreciate any help figuring out how to get this sub-module.

Cheers!

**Comment by cayennes** [comment]
Thanks, I've fixed it so these lines are showing properly:

       $ git submodule init
       $ git submodule update
